Working with questions
DasPivas/millionaire-project pull request #1
Opened 2022-03-27 20:43 UTC by DasPivas

2022-03-28 12:18 UTC, mcrozz requested changes

2022-03-28 12:18 UTC, mcrozz commented on src/components/PageLayout.tsx
> +const PageLayout: React.FC<Props> = ({children}) => {
Кажется в проекте не хватает какого-нибудь `.editorconfig`, чтоб количество пробелов не прыгало

2022-03-28 12:18 UTC, mcrozz commented on src/components/PageLayout.tsx
> +type Props = {
nip: `React.FC` в себе уже содержит `children`, его не обязательно указывать.

Ещё чем больше использовать типов — тем дольше со временем будет работать построение дерева для проверки типов. Такое лучше писать через интерфейсы — они ничего не стоят. Можно глянуть документацию, они немного поясняют их различие [1].

[1]: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces

2022-03-28 12:18 UTC, mcrozz commented on src/components/questions/qustions.ts
> +    .filter(question => !passQuestions?.includes(question.id))
nip: хоть массив не будет насколько большим, чтоб заметить разницу, но можно их объединить в один, чтоб проход был один раз [вместо двух проходов]

2022-03-28 12:18 UTC, mcrozz commented on src/components/questions/qustions.ts
> +import {getQuestions, QuestionDifficult} from "../../data/questions";
nip: стандартный шаблон не даёт просто писать `from "data/questions"`?

2022-03-28 12:18 UTC, mcrozz commented on src/components/questions/qustions.ts
> +export type TgetQuestion = [questionText: string, questionVariants: [string, string, string, string], questionId: number]
nip: (вкусновщина) кажется объект более легче поддерживать, чем массив типизированный, легче его будут понимать другие

2022-03-28 12:18 UTC, mcrozz commented on src/data/questions.ts
> +interface IQuestions {
[если что] можно называть интерфейсы не через `I`, эт только в C# требование (:

2022-03-28 12:18 UTC, mcrozz commented on src/data/questions.ts
> +    rightAnswer: 1
Если отдать заполнять json файл другому человеку, то возможна ошибка на единицу. Не все мыслят как разработчик, да и в некоторых языках программирования первый элемент массива начинается с единицы.

Кажется `variants` лучше превратить в список объектов. Можно его будет потом расширять и что-то добавлять, что относится именно к вопросам [допустим какие вопросы должны выбирать «зрители» и тому подобное]

2022-03-28 12:18 UTC, mcrozz commented on src/data/questions.ts
> +  return Questions
Хотелось избавиться от возможности изменения объекта?

2022-03-28 12:18 UTC, mcrozz commented on src/route/game/index.tsx
> +      <button className="question__answer-btn" onClick={()=>handelClick(0)}>
Не кажется, что какой-то повтор?

2022-03-28 12:18 UTC, mcrozz commented on src/route/game/index.tsx
> +const passQuestions: number[] = []
Возможно это хочется вогнать в какое-нибудь состояние? Сейчас получается бесконечное количество `GameWindow` имеет доступ к `passQuestions`, что пока нормально, но такие вещи будут плодиться потихоньку

2022-03-28 12:18 UTC, mcrozz commented on src/route/start/index.tsx
> +    return <button onClick={() => navigate('/game')} {...props}/>
nip: любые обработчики и любые такие функции лучше всего оборачивать в `useCallback` [^1], потому-что лямбда всё время пересоздаётся

[1]:https://reactjs.org/docs/hooks-reference.html#usecallback

2022-03-28 12:18 UTC, mcrozz commented on src/data/questions.ts
> +  easy,
Го превратим enum из int в string
```suggestion
  easy = 'easy',
```

2022-03-28 12:18 UTC, mcrozz commented on .gitignore
> +package-lock.json
Осуждаю 😅 , его нужно держать в репозитории, чтобы версии точно совпадали [и хэши]

2022-03-31 08:05 UTC, DasPivas commented on src/route/game/index.tsx
> +const passQuestions: number[] = []
В рамках следующей задачи буду выносить в контекст

2022-03-31 08:06 UTC, DasPivas commented on src/route/game/index.tsx
> +      <button className="question__answer-btn" onClick={()=>handelClick(0)}>
Пока сделал как и говорили через map

2022-03-31 08:06 UTC, DasPivas commented on src/components/questions/qustions.ts
> +export type TgetQuestion = [questionText: string, questionVariants: [string, string, string, string], questionId: number]
Поправил

2022-03-31 08:06 UTC, DasPivas commented on src/components/questions/qustions.ts
> +import {getQuestions, QuestionDifficult} from "../../data/questions";
Ругается ;(

2022-03-31 08:06 UTC, DasPivas commented on src/components/questions/qustions.ts
> +    .filter(question => !passQuestions?.includes(question.id))
Поправил

2022-03-31 08:06 UTC, DasPivas commented on src/components/PageLayout.tsx
> +type Props = {
Это к Арслану

2022-03-31 08:07 UTC, DasPivas commented on src/components/PageLayout.tsx
> +const PageLayout: React.FC<Props> = ({children}) => {
Это к Арслану

2022-03-31 08:07 UTC, DasPivas commented on src/data/questions.ts
> +  easy,
Поправил

2022-03-31 08:07 UTC, DasPivas commented on .gitignore
> +package-lock.json
Пофиксил

2022-04-03 13:22 UTC, mcrozz commented on src/components/questions/qustions.ts
> +import {getQuestions, QuestionDifficult} from "../../data/questions";
Мм, конфиг нужно подправить видимо. В `tsconfig.json` добавить строчку `"baseUrl": "./src"` в `compilerOptions`

2022-04-03 17:53 UTC, merged