Answer buttons highlighting
DasPivas/millionaire-project pull request #13
Opened 2022-04-24 12:19 UTC by arslan174

2022-04-24 13:30 UTC, mcrozz requested changes

2022-04-24 13:30 UTC, mcrozz commented on src/components/Timer/Timer.tsx
> +		<div className={classNames('timer', { expired: expired })} style={timerStyle}>
nip: если ключ и название переменной совпадает, то можно писать чисто название
```suggestion
		<div className={classNames('timer', { expired })} style={timerStyle}>
```

2022-04-24 13:30 UTC, mcrozz commented on src/components/button/style.scss
> +			0% {
Такое количество остановок в keyframes для чего?

2022-04-24 13:30 UTC, mcrozz commented on src/components/questions/index.ts
>  	const question = questions.filter((question) => question.id === id)[0];
nip: ой, нужно глянуть git blame на эту строчку. Есть же `find`, который возвращает объект или `undefined`

2022-04-24 13:30 UTC, mcrozz commented on src/route/game/index.tsx
> +		return 'basic';
Может внесём его в `AnswerStatuses`? И сделаем, чтобы функция возвращала только этот enum

2022-04-24 13:30 UTC, mcrozz commented on src/route/game/index.tsx
> +									<span className="text--primary">{`${variantsLabels[variant.id - 1]}: `}</span>
Для таких вещей лучше делать объект, который маппит ключ в значение.

И давай добавим подстилку, если `variant.id` оказался плохим

2022-04-24 13:30 UTC, mcrozz commented on src/route/game/index.tsx
> +						(variant.id === firstVariantId || variant.id === secondVariantId) && (
Для чего проверка на `firstVariantId` и `secondVariantId`?

2022-04-24 13:30 UTC, mcrozz commented on src/store/game-context.tsx
> +	gameMove: (isAnswerRight: boolean, secondsLeft: number) => void;
Получили побег логики из контекста (:

Внутри контекста можно понять, что игрок выбрал правильный ответ?

2022-04-24 13:45 UTC, arslan174 commented on src/components/button/style.scss
> +			0% {
Помигать выбранный вариант. На самом деле можно сделать одно мигание и повторить его через animation-iteration-count. Но в этой анимации сначала подсвечивается какое-то время выбранный вариант просто без миганий, если переписать на animation-iteration-count, то нужно будет задержку на установку статуса ставить, в зависимости от которого класс навешивается с анимацией

2022-04-24 13:45 UTC, arslan174 commented on src/components/Timer/Timer.tsx
> +		<div className={classNames('timer', { expired: expired })} style={timerStyle}>
удобно, поправлю

2022-04-24 13:59 UTC, arslan174 commented on src/components/questions/index.ts
>  	const question = questions.filter((question) => question.id === id)[0];
а, ну да, поправлю

2022-04-24 21:07 UTC, arslan174 commented on src/store/game-context.tsx
> +	gameMove: (isAnswerRight: boolean, secondsLeft: number) => void;
вынес в контекст

2022-04-24 21:07 UTC, arslan174 commented on src/route/game/index.tsx
> +						(variant.id === firstVariantId || variant.id === secondVariantId) && (
переделал

2022-04-24 21:08 UTC, arslan174 commented on src/route/game/index.tsx
> +									<span className="text--primary">{`${variantsLabels[variant.id - 1]}: `}</span>
заменил массив на объект

2022-04-24 21:09 UTC, arslan174 commented on src/route/game/index.tsx
> +		return 'basic';
Тут все же решил не менять, AnswerStatuses описывают статус ответа, а не конкретные статусы кнопок

2022-04-25 07:03 UTC, mcrozz commented on src/route/game/index.tsx
> +		return 'basic';
Можно тогда создать другой `enum,` который будет расширять (:

Тут цель в том, чтобы детерминировать тип. У тебя ide даже начнёт подсказывать значения в таких случаях. Сейчас потребители видят только то, что функция возвращает `string`, т.е. произвольный текст

2022-04-25 07:09 UTC, mcrozz commented on src/route/game/index.tsx
> +						{...{
Такие определения проще при дублировании ключей, но есть мелкая проблема — попробуй закинуть в этот объект, допустим, `switchWindow`. По логике вещей ts должен поорать, что передаёт то, что не указано в пропсах, но… будет ли он так делать?

2022-04-25 07:09 UTC, mcrozz commented on src/components/context/index.tsx
> +	useEffect(() => {
Интересный подход, ничего против его не имею, я бы прописал простановку рядом с тем местом, где мы выставляем `questionId`

2022-04-25 11:36 UTC, arslan174 commented on src/route/game/index.tsx
> +		return 'basic';
Пытался создать другой энам. Или тип, который экстендит этот, но так вообще некрасиво. Сделал просто возвращаемым AnswerStatus, а вместо 'basic' использую 'no-answer'

2022-04-25 11:55 UTC, arslan174 commented on src/components/context/index.tsx
> +	useEffect(() => {
Можно добавить в другой useEffect, который зависит от questionId, но тот эффект зависит еще и от других стейтов, будут происходить лишние вызовы методы getRightAnswer, например, когда windowState меняем. Можно конечно мемоизировать результат getRightAnswer, но кажется отдельным useEffect попроще. Плюс, в том useEffect происходит немного другая логика - поддержание local storage в актуальном состоянии, не хочется смешивать

2022-04-25 12:06 UTC, arslan174 commented on src/route/game/index.tsx
> +						{...{
вынес в функцию
` getButtonsContainerProps = (questionVariants: IVariants[]): ButtonsContainerProps`

2022-04-25 13:36 UTC, mcrozz approved these changes

2022-04-25 13:40 UTC, merged