Create hins
DasPivas/millionaire-project pull request #16
Opened 2022-04-26 14:30 UTC by DasPivas

2022-04-26 16:43 UTC, mcrozz requested changes

2022-04-26 16:43 UTC, mcrozz commented on src/components/CallHint/phrases.ts
> +	return phrases[getRandom(phrases.length)].replace('%', insertStr);
«Я на 100% уверен, что это %» 😄

2022-04-26 16:43 UTC, mcrozz commented on src/components/questions/index.ts
> +	return questions.filter((question) => question.id === id)[0];
Есть же find, который возвращает объект (:

2022-04-26 16:43 UTC, mcrozz commented on src/components/questions/index.ts
> +		switch (value) {
Кажется в виде объекта это выглядело бы лаконичнее

2022-04-26 16:43 UTC, mcrozz commented on src/components/Hints/index.tsx
> +			{Object.keys(availableHints).map((item: string, i: number) => {
Есть ещё `Object.entries`, чтобы получить сразу же ключ и значение

2022-04-26 16:43 UTC, mcrozz commented on src/components/Hints/index.tsx
> +						key={i}
А не `item`?

2022-04-26 16:43 UTC, mcrozz commented on src/components/questions/index.ts
> +	return questions.filter((question) => question.id === id)[0];
И сейчас когда с мастера будешь подливать — @arslan174 это уже правил

2022-04-26 16:43 UTC, mcrozz commented on src/components/questions/index.ts
> +		countQuestion = 4;
Категорически против объединять определения таким образом. Читаемость убивается

2022-04-26 16:43 UTC, mcrozz commented on src/components/questions/index.ts
> +const getViewerHint = (
Вот такие функции можно покрывать тестами, чтобы бизнесовая логика не ломалась со временем. Тут не нужно прямо писать тесты, просто nip

2022-04-26 16:43 UTC, mcrozz commented on src/route/game/index.tsx
> +					setTimeout(() => {
Многие забывают про аргументы `setTimeout`, что второй и последующие аргументы отправляются в саму функцию:
```suggestion
					setTimeout(setPaused, 2000, false);
```

2022-04-26 16:43 UTC, mcrozz commented on src/route/game/index.tsx
> +					console.error('Получен неизвестный тип подсказки');
И всё равно плохое имя прокинули в логику? [88 строчка]

2022-04-26 16:43 UTC, mcrozz commented on src/route/game/index.tsx
> +	const variantIdToLabel = Object.freeze({ 1: 'A', 2: 'B', 3: 'C', 4: 'D' });
Может пора вытащить вне компонента? Можно этот объект переиспользовать вместо `switchAnswer`.

И для чего заморозка?

2022-04-26 16:43 UTC, mcrozz commented on src/route/game/index.tsx
> +						{(!fiftyHint || variant.fiftyHint) && (
Дублирующуюся логику можно выносить в переменную, так можно поднять читаемость и более быть уверенным, что логику менять только в одном месте нужно

2022-04-26 16:43 UTC, mcrozz commented on src/route/start/index.tsx
> +					srcSet={`${logoOptimizeWebp}, ${logoWebp} 2x`}
nip: можно webpack научить самостоятельно создавать оптимизированные версии фоток

2022-04-26 16:43 UTC, mcrozz commented on src/store/game-context.tsx
> +const defaultViewerHint: TViewerHint = Object.freeze({
Честно, не встречали проблемы с использованием чисто объекта, без такого оборачивания в заморозку. Webpack и так гарантирует при импорте выполнение кода один раз [сколько раз не делали импорт модуля]

2022-04-26 17:54 UTC, DasPivas commented on src/components/questions/index.ts
> +		countQuestion = 4;
Ну prettier же по строчкам разносит)
Поправлю

2022-04-26 18:15 UTC, DasPivas commented on src/route/game/index.tsx
> +	const variantIdToLabel = Object.freeze({ 1: 'A', 2: 'B', 3: 'C', 4: 'D' });
Что бы сложно было изменить константу на которой логика строится

2022-04-26 18:16 UTC, DasPivas commented on src/route/start/index.tsx
> +					srcSet={`${logoOptimizeWebp}, ${logoWebp} 2x`}
Ну пока ручки тренируем)

2022-04-26 18:20 UTC, DasPivas commented on src/store/game-context.tsx
> +const defaultViewerHint: TViewerHint = Object.freeze({
Можно оставлю, чтобы спать спокойнее потом?)

2022-04-27 07:11 UTC, mcrozz commented on src/components/CallHint/phrases.ts
> +	if (insertStr === undefined) {
Пустую строку тоже считаем валидной?

2022-04-27 07:24 UTC, mcrozz commented on src/route/game/index.tsx
> +	const variantIdToLabel = Object.freeze({ 1: 'A', 2: 'B', 3: 'C', 4: 'D' });
Должен быть мотив, чтобы человек хотел поменять (:

2022-04-27 10:29 UTC, mcrozz approved these changes

2022-04-27 10:30 UTC, merged