Start page
DasPivas/millionaire-project pull request #2
Opened 2022-03-28 10:04 UTC by arslan174

2022-03-28 12:29 UTC, mcrozz requested changes

2022-03-28 12:29 UTC, mcrozz commented on src/components/PageLayout.css
> +    height: 100vh;
Тут будут развлечения на мобилках, допустим на iOS Safari. `vh` для них немного другое значение имеет

https://dev.to/maciejtrzcinski/100vh-problem-with-ios-safari-3ge9

2022-03-28 12:29 UTC, mcrozz commented on src/components/PageLayout.css
> +    height: 100vh;
И кажется начиная с каково-то разрешения даже если занимаешь весь экран — может не хватить. Допустим возьми телефон и переверни его в горизонтальное положение

2022-03-28 12:29 UTC, mcrozz commented on src/components/PageLayout.tsx
> +type Props = {
Можно не указывать children, более описал тут: https://github.com/DasPivas/millionaire-project/pull/1#discussion_r836341323

2022-03-28 12:29 UTC, mcrozz commented on src/route/start/index.tsx
> +    return <button onClick={() => navigate('/game')} {...props}/>
nip: тоже про `useCallback` против лямбд, https://github.com/DasPivas/millionaire-project/pull/1#discussion_r836361515

2022-04-02 17:58 UTC, arslan174 commented on src/components/PageLayout.css
> +    height: 100vh;
сделал через position: absolute, чтобы у всех содержащих блоков не делать height: 100%

2022-04-02 17:58 UTC, arslan174 commented on src/components/PageLayout.tsx
> +type Props = {
поправил

2022-04-02 17:59 UTC, arslan174 commented on src/route/start/index.tsx
> +    return <button onClick={() => navigate('/game')} {...props}/>
поправил. Но правильно понимаю, что так без useMemo практической пользы особо нет в useCallback?

2022-04-03 07:32 UTC, mcrozz commented on src/route/start/index.tsx
> +    return <button onClick={() => navigate('/game')} {...props}/>
Без оборачивания компонента в `React.memo`? Почему, есть польза — react не будет отписывать и снова подписывать обработчик `click` события на каждый рендер компонента

2022-04-03 07:38 UTC, mcrozz commented on src/components/PageLayout.css
> +    height: 100vh;
Ладно, потом, на стадии шлифовки, глянем как это будет выглядеть на разных экранах

2022-04-03 07:40 UTC, mcrozz approved these changes

2022-04-03 08:26 UTC, merged